# Generated by Django 3.1.4 on 2021-06-24 13:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('candidates_count', models.IntegerField(default=0)),
                ('result', models.CharField(choices=[('S', 'Selected'), ('R', 'Rejected'), ('J', 'Joined'), ('DNJ', 'Did Not Join'), ('TBD', 'Pending')], default='TBD', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=40)),
                ('college', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.CharField(max_length=40, null=True)),
                ('position_applied', models.CharField(blank=True, max_length=30, null=True)),
                ('resume', models.FileField(null=True, upload_to='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewParticipants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pariticipant_one', to='Interviews.participant')),
                ('candidate_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pariticipant_two', to='Interviews.participant')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='Interviews.interview')),
            ],
        ),
    ]
